services:
  - type: web
    name: torneo-galactico-front
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist/frontend/browser
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
